import Head from 'next/head'
import { About } from 'src/components/About'
import { Footer } from 'src/components/Footer'
import { Header } from 'src/components/Header'
import { Navbar } from 'src/components/Navbar'
import { Projects } from 'src/components/Projects'
import { Skills } from 'src/components/Skills'
import client from 'src/sanity.js'
  


export default function Home({header, about, skills, projects, footer}) {
  return (
    <>
      <Head>
        <title>Portifolio Claudio Lins</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col justify-center items-center min-h-screen w-full'>
        <Navbar />
        <Header header={header}/>
        <About about={about}/>
        <Skills skills={skills}/>
        <Projects projects={projects} />
        <Footer footer={footer}/>
      </main>
      {/* <pre>
        {JSON.stringify(projects, null, 2)}
      </pre> */}
    </>
  )
}

export const getStaticProps = async () => {
  const header = await client.fetch(`*[_type == "header"][0]`)
  const about = await client.fetch(`*[_type == "about"][0]`)
  const skills = await client.fetch(`*[_type == "skills"][0]`)
  const projects = await client.fetch(`*[_type == "projects"][0]`)
  const footer = await client.fetch(`*[_type == "footer"][0]`)
  return {
    props: {
      header,
      about,
      skills,
      projects,
      footer
    },
  }
}